syntax = "proto3";

package dapr.proto.runtime.v1;
import "google/protobuf/any.proto";
import "google/protobuf/empty.proto";
import "google/protobuf/timestamp.proto";
import "dapr/proto/common/v1/common.proto";
import "dapr/proto/runtime/v1/appcallback.proto";

option csharp_namespace = "Dapr.Client.Autogen.Grpc.v1";
option java_outer_classname = "DaprProtos";
option java_package = "io.dapr.v1";
option go_package = "github.com/dapr/dapr/pkg/proto/runtime/v1;runtime";




///////////////////////////////////////////////////////////////////////



message Strings {
  repeated string values = 1;
}

message RequestHeaders {
  map<string, Strings> values = 1;
}

message ResponseHeaders {
  ResponseStatus status = 1;
  string message = 2;
  map<string, Strings> values = 3;
}

enum ResponseStatus {
  SUCCESS = 0;  // 执行成功
  ERROR = 1;    // 执行错误
  EVENT_DUPLICATE = 2; // 事件已经存在，被重复执行，
}

////////////////////

// LoadDomainEvent

message LoadDomainEventRequest {
  string comp_name = 1;
  string tenant_id = 2;
  string aggregate_id = 3;
  string aggregate_type = 4;
  uint64 sequence_number = 5;
  uint64 page_num = 6;
  uint64 page_size = 7;
  bool is_total_rows = 8;
  RequestHeaders headers = 100;
}

message LoadDomainEventResponse{

  message SnapshotDto {
    string aggregate_data = 1;     // json format
    string aggregate_revision = 2;
    uint64 sequence_number = 3;
    string metadata = 4;
  }

  message EventDto {
    string event_id = 1;
    string event_data = 2;  // json format
    string event_type = 3;
    string event_version = 4;
    uint64 sequence_number = 5;
  }

  ResponseHeaders headers = 1;
  string tenant_id = 4;
  string aggregate_id = 5;
  string aggregate_type = 6;
  SnapshotDto snapshot = 7;
  repeated EventDto events = 8;
  uint64 page_num = 9;
  uint64 page_size = 10;
  uint64 total_rows = 11;
  uint64 total_pages = 12;

}

// SaveDomainEventSnapshot

message SaveDomainEventSnapshotRequest{
  RequestHeaders headers = 100;
  string comp_name = 1;
  string tenant_id = 2;
  string aggregate_id = 3;
  string aggregate_type = 4;
  string aggregate_data = 5; // json format
  string aggregate_version = 6;
  uint64 sequence_number = 7;
  string metadata = 8;
}

message SaveDomainEventSnapshotResponse{
  ResponseHeaders headers = 1;
}

// Commit
message CommitDomainEventsRequest {
  RequestHeaders headers = 100;
  string comp_name = 1;
  string session_id = 2;
  string tenant_id = 3;
}

message CommitDomainEventsResponse {
  ResponseHeaders headers = 1;
}

//  Rollback

message RollbackDomainEventsRequest {
  RequestHeaders headers = 100;
  string comp_name = 1;
  string session_id = 2;
  string tenant_id = 3;
}

message RollbackDomainEventsResponse {
  ResponseHeaders headers = 1;
}

// ApplyDomainEvent

message ApplyDomainEventRequest{
  RequestHeaders headers = 100;
  string comp_name = 1;
  string session_id = 3;
  string tenant_id = 4;
  string aggregate_id = 5;
  string aggregate_type = 6;
  repeated EventDto events = 7;
}

message ApplyDomainEventResponse{
  ResponseHeaders headers = 1;
}

// CreateEvent

message CreateEventRequest{
  RequestHeaders headers = 100;
  string comp_name = 1;
  string tenant_id = 2;
  string aggregate_id = 3;
  string aggregate_type = 4;
  repeated EventDto events = 5;
}

message CreateEventResponse{
  ResponseHeaders headers = 1;
}

// DeleteEvent

message DeleteEventRequest{
  RequestHeaders headers = 100;
  string comp_name = 1;
  string tenant_id = 2;
  string aggregate_id = 3;
  string aggregate_type = 4;
  EventDto event = 5;
}

message DeleteEventResponse{
  ResponseHeaders headers = 1;
}

message EventDto {
  string apply_type = 1;  // 事件应用类型  "create":创建聚合根; "apply":应用业务事件; "delete":聚合根删除事件
  string event_id = 2;
  string command_id = 3;
  string event_data = 4;   // json format
  string event_type = 5;
  string event_version = 6;
  google.protobuf.Timestamp  event_time = 7;
  string pubsub_name = 8;
  string topic = 9;
  string metadata = 10;  // json format
  map<string, string> relations = 11; // aggregate relations
  bool is_sourcing = 12; // event sourcing
}

// EventType
/*
message EventTypeDto {
  string id=1;
  string title=2;
  string version=3;
  string aggregate_type=4;
  map<string, string> properties=5;
  string description=6;
  bool is_sourcing=7;
}*/


// GetDomainEventRelations

message GetDomainEventRelationsRequest {
  RequestHeaders headers = 100;
  string comp_name = 1;
  string tenant_id = 2;
  string aggregate_type = 3;
  string filter = 4;
  string sort = 5;
  uint64 pageNum = 6;
  uint64 pageSize = 7;
}

message GetDomainEventRelationsResponse {
  ResponseHeaders headers = 1;
  repeated RelationDto data = 2;
  uint64 total_rows = 3;
  uint64 total_pages = 4;
  uint64 page_num = 5;
  uint64 page_size = 6;
  string filter = 7;
  string sort = 8;
  string error = 9;
  bool is_found = 10;
}


message RelationDto {
  string id = 1;
  string tenant_id = 2;
  string table_name = 3;
  string aggregate_id = 4;
  string aggregate_type = 5;
  bool is_deleted = 6;
  string rel_name = 7 ;  // 关系名
  string rel_value = 8; // 关系值
}

// GetDomainEvents

message GetDomainEventsRequest {
  RequestHeaders headers = 100;
  string comp_name = 1;
  string tenant_id = 2;
  string aggregate_type = 3;
  string filter = 4;
  string sort = 5;
  uint64 page_num = 6;
  uint64 page_size = 7;
  bool is_total_rows = 8;
}

message GetDomainEventsResponse {
  ResponseHeaders headers = 1;
  repeated GetDomainEventsItemDto data = 2;
  uint64 total_rows = 3;
  uint64 total_pages = 4;
  uint64 page_num = 5;
  uint64 page_size = 6;
  string filter = 7;
  string sort = 8;
  string error = 9;
  bool is_found = 10;
}

message GetDomainEventsItemDto {
  string event_id = 1;
  string command_id = 2;
  string event_data = 3;   // json format
  string event_type = 4;
  string event_version = 5;
  google.protobuf.Timestamp  event_time = 6;
  string pubsub_name = 7;
  string topic = 8;
  string metadata = 9;  // json format
}


// Application Log
message WriteAppEventLogRequest{
  RequestHeaders headers = 100;
  string comp_name = 1;
  string tenant_id = 2;
  string id = 3;
  string app_id = 4;

  string class = 5;
  string func = 6;

  string level = 7;
  google.protobuf.Timestamp  time = 8;
  bool status = 9;
  string message = 10;

  string pub_app_id = 11;
  string event_id = 12;
  string command_id = 13;

}

message WriteAppEventLogResponse{
  ResponseHeaders headers = 1;
}

message UpdateAppEventLogRequest {
  RequestHeaders headers = 100;
  string comp_name = 1;
  string tenant_id = 2;
  string id = 3;
  string app_id = 4;
  string class = 5;
  string func = 6;
  string level = 7;
  google.protobuf.Timestamp time = 8;
  bool status = 9;
  string message = 10;
  string pub_app_id = 11;
  string event_id = 12;
  string command_id = 13;
}

message UpdateAppEventLogResponse {
  ResponseHeaders headers = 1;
}



// GetAppEventLogByCommandId

message GetAppEventLogByCommandIdRequest {
  RequestHeaders headers = 100;
  string comp_name = 1;
  string tenant_id = 2;
  string app_id = 3;
  string command_id = 4;
}

message GetAppEventLogByCommandIdResponse {

  message EventLogDto {
    string tenant_id = 1;
    string id = 2;
    string app_id = 3;
    string class = 4;
    string func = 5;
    string level = 6;
    google.protobuf.Timestamp time = 7;
    bool status = 8;
    string message = 9;

    string pub_app_id = 10;
    string event_id = 11;
    string command_id = 12;
  }
  ResponseHeaders headers = 1;
  repeated EventLogDto data = 2;
}


//  WriteAppLog
message WriteAppLogRequest {
  RequestHeaders headers = 100;
  string comp_name = 1;
  string tenant_id = 2;
  string id = 3;
  string app_id = 4;
  string class = 5;
  string func = 6;
  string level = 7;
  google.protobuf.Timestamp time = 8;
  bool status = 9;
  string message = 10;
}

message WriteAppLogResponse {
  ResponseHeaders headers = 1;
}

message UpdateAppLogRequest {
  RequestHeaders headers = 100;
  string comp_name = 1;
  string tenant_id = 2;
  string id = 3;
  string app_id = 4;
  string class = 5;
  string func = 6;
  string level = 7;
  google.protobuf.Timestamp time = 8;
  bool status = 9;
  string message = 10;
}

message UpdateAppLogResponse {
  ResponseHeaders headers = 1;
}

// GetAppLogById

message GetAppLogByIdRequest {
  RequestHeaders headers = 100;
  string comp_name = 1;
  string tenant_id = 2;
  string id = 3;
}

message GetAppLogByIdResponse {
  ResponseHeaders headers = 1;
  string tenant_id = 2;
  string id = 3;
  string app_id = 4;
  string class = 5;
  string func = 6;
  string level = 7;
  google.protobuf.Timestamp time = 8;
  bool status = 9;
  string  message = 10;
}


message CommandRequest {
  RequestHeaders headers = 100;
  string command = 1;
  map<string, string> options=2;
}

message CommandResponse {
  RequestHeaders headers = 100;
  uint64 status = 1;
  map<string, string> data=2;
  string error = 3;
}