// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.3
// source: dapr/proto/runtime/v1/dapr.proto

package runtime

import (
	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// Dapr_ServiceDesc is the grpc.ServiceDesc for Dapr service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Dapr_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dapr.proto.runtime.v1.Dapr",
	HandlerType: (*DaprServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InvokeService",
			Handler:    _Dapr_InvokeService_Handler,
		},
		{
			MethodName: "GetState",
			Handler:    _Dapr_GetState_Handler,
		},
		{
			MethodName: "GetBulkState",
			Handler:    _Dapr_GetBulkState_Handler,
		},
		{
			MethodName: "SaveState",
			Handler:    _Dapr_SaveState_Handler,
		},
		{
			MethodName: "QueryStateAlpha1",
			Handler:    _Dapr_QueryStateAlpha1_Handler,
		},
		{
			MethodName: "DeleteState",
			Handler:    _Dapr_DeleteState_Handler,
		},
		{
			MethodName: "DeleteBulkState",
			Handler:    _Dapr_DeleteBulkState_Handler,
		},
		{
			MethodName: "ExecuteStateTransaction",
			Handler:    _Dapr_ExecuteStateTransaction_Handler,
		},
		{
			MethodName: "PublishEvent",
			Handler:    _Dapr_PublishEvent_Handler,
		},
		{
			MethodName: "BulkPublishEventAlpha1",
			Handler:    _Dapr_BulkPublishEventAlpha1_Handler,
		},
		{
			MethodName: "InvokeBinding",
			Handler:    _Dapr_InvokeBinding_Handler,
		},
		{
			MethodName: "GetSecret",
			Handler:    _Dapr_GetSecret_Handler,
		},
		{
			MethodName: "GetBulkSecret",
			Handler:    _Dapr_GetBulkSecret_Handler,
		},
		{
			MethodName: "RegisterActorTimer",
			Handler:    _Dapr_RegisterActorTimer_Handler,
		},
		{
			MethodName: "UnregisterActorTimer",
			Handler:    _Dapr_UnregisterActorTimer_Handler,
		},
		{
			MethodName: "RegisterActorReminder",
			Handler:    _Dapr_RegisterActorReminder_Handler,
		},
		{
			MethodName: "UnregisterActorReminder",
			Handler:    _Dapr_UnregisterActorReminder_Handler,
		},
		{
			MethodName: "RenameActorReminder",
			Handler:    _Dapr_RenameActorReminder_Handler,
		},
		{
			MethodName: "GetActorState",
			Handler:    _Dapr_GetActorState_Handler,
		},
		{
			MethodName: "ExecuteActorStateTransaction",
			Handler:    _Dapr_ExecuteActorStateTransaction_Handler,
		},
		{
			MethodName: "InvokeActor",
			Handler:    _Dapr_InvokeActor_Handler,
		},
		{
			MethodName: "GetConfigurationAlpha1",
			Handler:    _Dapr_GetConfigurationAlpha1_Handler,
		},
		{
			MethodName: "GetConfiguration",
			Handler:    _Dapr_GetConfiguration_Handler,
		},
		{
			MethodName: "UnsubscribeConfigurationAlpha1",
			Handler:    _Dapr_UnsubscribeConfigurationAlpha1_Handler,
		},
		{
			MethodName: "UnsubscribeConfiguration",
			Handler:    _Dapr_UnsubscribeConfiguration_Handler,
		},
		{
			MethodName: "TryLockAlpha1",
			Handler:    _Dapr_TryLockAlpha1_Handler,
		},
		{
			MethodName: "UnlockAlpha1",
			Handler:    _Dapr_UnlockAlpha1_Handler,
		},
		{
			MethodName: "GetMetadata",
			Handler:    _Dapr_GetMetadata_Handler,
		},
		{
			MethodName: "SetMetadata",
			Handler:    _Dapr_SetMetadata_Handler,
		},
		{
			MethodName: "SubtleGetKeyAlpha1",
			Handler:    _Dapr_SubtleGetKeyAlpha1_Handler,
		},
		{
			MethodName: "SubtleEncryptAlpha1",
			Handler:    _Dapr_SubtleEncryptAlpha1_Handler,
		},
		{
			MethodName: "SubtleDecryptAlpha1",
			Handler:    _Dapr_SubtleDecryptAlpha1_Handler,
		},
		{
			MethodName: "SubtleWrapKeyAlpha1",
			Handler:    _Dapr_SubtleWrapKeyAlpha1_Handler,
		},
		{
			MethodName: "SubtleUnwrapKeyAlpha1",
			Handler:    _Dapr_SubtleUnwrapKeyAlpha1_Handler,
		},
		{
			MethodName: "SubtleSignAlpha1",
			Handler:    _Dapr_SubtleSignAlpha1_Handler,
		},
		{
			MethodName: "SubtleVerifyAlpha1",
			Handler:    _Dapr_SubtleVerifyAlpha1_Handler,
		},
		{
			MethodName: "StartWorkflowAlpha1",
			Handler:    _Dapr_StartWorkflowAlpha1_Handler,
		},
		{
			MethodName: "GetWorkflowAlpha1",
			Handler:    _Dapr_GetWorkflowAlpha1_Handler,
		},
		{
			MethodName: "PurgeWorkflowAlpha1",
			Handler:    _Dapr_PurgeWorkflowAlpha1_Handler,
		},
		{
			MethodName: "TerminateWorkflowAlpha1",
			Handler:    _Dapr_TerminateWorkflowAlpha1_Handler,
		},
		{
			MethodName: "PauseWorkflowAlpha1",
			Handler:    _Dapr_PauseWorkflowAlpha1_Handler,
		},
		{
			MethodName: "ResumeWorkflowAlpha1",
			Handler:    _Dapr_ResumeWorkflowAlpha1_Handler,
		},
		{
			MethodName: "RaiseEventWorkflowAlpha1",
			Handler:    _Dapr_RaiseEventWorkflowAlpha1_Handler,
		},
		{
			MethodName: "StartWorkflowBeta1",
			Handler:    _Dapr_StartWorkflowBeta1_Handler,
		},
		{
			MethodName: "GetWorkflowBeta1",
			Handler:    _Dapr_GetWorkflowBeta1_Handler,
		},
		{
			MethodName: "PurgeWorkflowBeta1",
			Handler:    _Dapr_PurgeWorkflowBeta1_Handler,
		},
		{
			MethodName: "TerminateWorkflowBeta1",
			Handler:    _Dapr_TerminateWorkflowBeta1_Handler,
		},
		{
			MethodName: "PauseWorkflowBeta1",
			Handler:    _Dapr_PauseWorkflowBeta1_Handler,
		},
		{
			MethodName: "ResumeWorkflowBeta1",
			Handler:    _Dapr_ResumeWorkflowBeta1_Handler,
		},
		{
			MethodName: "RaiseEventWorkflowBeta1",
			Handler:    _Dapr_RaiseEventWorkflowBeta1_Handler,
		},
		{
			MethodName: "Shutdown",
			Handler:    _Dapr_Shutdown_Handler,
		},
		{
			MethodName: "ApplyDomainEvent",
			Handler:    _Dapr_ApplyDomainEvent_Handler,
		},
		{
			MethodName: "LoadDomainEvent",
			Handler:    _Dapr_LoadDomainEvent_Handler,
		},
		{
			MethodName: "SaveDomainEventSnapshot",
			Handler:    _Dapr_SaveDomainEventSnapshot_Handler,
		},
		{
			MethodName: "CommitDomainEvents",
			Handler:    _Dapr_CommitDomainEvents_Handler,
		},
		{
			MethodName: "RollbackDomainEvents",
			Handler:    _Dapr_RollbackDomainEvents_Handler,
		},
		{
			MethodName: "GetDomainEventRelations",
			Handler:    _Dapr_GetDomainEventRelations_Handler,
		},
		{
			MethodName: "GetDomainEvents",
			Handler:    _Dapr_GetDomainEvents_Handler,
		},
		{
			MethodName: "WriteAppEventLog",
			Handler:    _Dapr_WriteAppEventLog_Handler,
		},
		{
			MethodName: "UpdateAppEventLog",
			Handler:    _Dapr_UpdateAppEventLog_Handler,
		},
		{
			MethodName: "GetAppEventLogByCommandId",
			Handler:    _Dapr_GetAppEventLogByCommandId_Handler,
		},
		{
			MethodName: "WriteAppLog",
			Handler:    _Dapr_WriteAppLog_Handler,
		},
		{
			MethodName: "UpdateAppLog",
			Handler:    _Dapr_UpdateAppLog_Handler,
		},
		{
			MethodName: "GetAppLogById",
			Handler:    _Dapr_GetAppLogById_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeConfigurationAlpha1",
			Handler:       _Dapr_SubscribeConfigurationAlpha1_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SubscribeConfiguration",
			Handler:       _Dapr_SubscribeConfiguration_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "EncryptAlpha1",
			Handler:       _Dapr_EncryptAlpha1_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "DecryptAlpha1",
			Handler:       _Dapr_DecryptAlpha1_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "dapr/proto/runtime/v1/dapr.proto",
}
